
# This file is automatically generated, you probably don't want to edit this

myRegressionOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "myRegressionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            dep = NULL,
            covs = NULL, ...) {

            super$initialize(
                package="COOLj",
                name="myRegression",
                requiresData=TRUE,
                ...)

            private$..dep <- jmvcore::OptionVariable$new(
                "dep",
                dep,
                permitted=list(
                    "numeric"))
            private$..covs <- jmvcore::OptionVariables$new(
                "covs",
                covs,
                suggested=list(
                    "continuous",
                    "ordinal"),
                permitted=list(
                    "numeric"))

            self$.addOption(private$..dep)
            self$.addOption(private$..covs)
        }),
    active = list(
        dep = function() private$..dep$value,
        covs = function() private$..covs$value),
    private = list(
        ..dep = NA,
        ..covs = NA)
)

myRegressionResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "myRegressionResults",
    inherit = jmvcore::Group,
    active = list(
        coefficients = function() private$.items[["coefficients"]],
        anova = function() private$.items[["anova"]],
        effects = function() private$.items[["effects"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Regression analysis")
            self$add(jmvcore::Table$new(
                options=options,
                name="coefficients",
                title="Parameter Estimates (Coefficients)",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="coef", 
                        `title`="Estimate", 
                        `type`="number"),
                    list(
                        `name`="se", 
                        `title`="SE", 
                        `type`="number"),
                    list(
                        `name`="t", 
                        `title`="t", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="anova",
                title="ANOVA table",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="test", 
                        `title`="F-test", 
                        `type`="number", 
                        `format`="zto"),
                    list(
                        `name`="df1", 
                        `title`="df", 
                        `type`="integer"),
                    list(
                        `name`="df2", 
                        `title`="dfres", 
                        `type`="integer"),
                    list(
                        `name`="p", 
                        `title`="p", 
                        `type`="number", 
                        `format`="zto,pvalue"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="effects",
                title="Effect Size Indices",
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Variable", 
                        `type`="text"),
                    list(
                        `name`="index", 
                        `title`="Index", 
                        `type`="text"),
                    list(
                        `name`="value", 
                        `title`="Value", 
                        `type`="number", 
                        `format`="zto"))))}))

myRegressionBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "myRegressionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "COOLj",
                name = "myRegression",
                version = c(1,0,0),
                options = options,
                results = myRegressionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Regression analysis
#'
#' 
#' @param data .
#' @param dep .
#' @param covs .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$coefficients} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$anova} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$effects} \tab \tab \tab \tab \tab a table \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$coefficients$asDF}
#'
#' \code{as.data.frame(results$coefficients)}
#'
#' @export
myRegression <- function(
    data,
    dep,
    covs) {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("myRegression requires jmvcore to be installed (restart may be required)")

    if ( ! missing(dep)) dep <- jmvcore::resolveQuo(jmvcore::enquo(dep))
    if ( ! missing(covs)) covs <- jmvcore::resolveQuo(jmvcore::enquo(covs))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(dep), dep, NULL),
            `if`( ! missing(covs), covs, NULL))


    options <- myRegressionOptions$new(
        dep = dep,
        covs = covs)

    analysis <- myRegressionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

